import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>nextsj church pnja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-violet-500 font-extrabold text-2xl">Hi there!</h1>
    </div>
  );
}
