import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className="min-h-screen bg-slate-900 text-slate-400">
      <Head>
        <title>nextjs church pnja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="min-h-[600px]">main</main>
      <Footer />
    </div>
  );
}
